---
- name: install packages on webservers
  hosts: webservers
  become: true
  tasks:
  - name: install tree
    yum:
   #  name: ['tree','git','gzip','wget']
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - make
      - gzip
      - telnet

