---
- name: install packages on webservers
  hosts: webservers
  become: true
  tasks:
  - name: stop httpd
    service:
      name: httpd
      state: stopped
  - name: uninstall httpd
    yum:
      name: httpd
      state: removed


