---
- hosts: dbservers
  become: true
  tasks:
  - name: Install firewall mariadb
    yum:
      name: 
         - firewalld
         - mariadb-server
         - MySQL-python
      state: installed

  - name: start and enable firewall 
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: start and enable  mariabd
    service:
      name: mariadb
      state: started
      enabled: yes


  - name: Configure firewall for Database
    firewalld:
       port: 3306/tcp
       permanent: true
       zone: public
       immediate: true
       state: enabled

  - name: create database 
    mysql_db:
       name: ecomdb
       state: present

  - name: create user
    mysql_user:
       name: 'ecomuser'
       password: ecompassword
       priv: '*.*:ALL,GRANT'
       host: '172-31-87-212'
       state: present

  - name: Move db-load-script to db host
    copy:
      src: /opt/ansible/db-load-script.sql
      dest: /tmp/db-load-script.sql

  - name: Load Inventory Data
    shell: mysql -f < /tmp/db-load-script.sql
