---
- name: this playbook is to create users on hosts
  hosts: all
  become: true
  vars_files:
          - user.yml
  tasks:
  - name: create new users in hosts
    user: 
      name: "{{ user }}"
      state: present
