---
- name: install and start apache2 on ubuntu servers using notify handler
  hosts: ubuntu
  become: true
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present
    notify: start apache2

  handlers:
  - name: start apache2
    service:
      name: apache2
      state: started


