---
- name: stop and uninstall httpd on webservers
  hosts: redhat
  become: true
  tasks:
  - name: stop httpd
    service:
      name: httpd
      state: stopped

  - name: uninstall httpd
    yum:
      name: httpd
      state: removed


