---
- name: ansible playbook to test ansible vault
  hosts: all
  become: true
  vars_files:
      - vault-pass.yml
  tasks: 
  - name: clone a repo
    git:
     repo: https://kalyansgithub:{{ password }}@github.com/KalyansGithub/hello-world.git
     dest: /opt/ansadmin/test-vault
