-
  name: Deploy a web application
  hosts: db_and_web_server
  become: true
  tasks:
    - name: Install dependencies
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
       - python
       - python-setuptools
       - python-dev
       - build-essential
       - python-pip
       - python-mysqldb

    - include: tasks/db_deploy.yml

    - include: tasks/web_deploy.yml
